[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
manager = "GdWp89pQC5n36HAznAYxqE6ev9dGvrH2cPMn5BQjJ6nW"
rps = "63BgSDqQVJdfX9HDsxFUKJfjt45pnEPpT2CoWMwPNsho"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
