[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
prost = "0.11"
shared = { path = "../shared" }
anyhow = "1.0.97"
ratatui = "0.29.0"
