[package]
name = "solve"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.0"
corcoin = { path = "../program/programs/corcoin", features = ["cpi"] }

[lib]
crate-type = ["cdylib", "lib"]
