[package]
name = "solver"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
prost = "0.11"
prost-types = "0.11"

[build-dependencies]
prost-build = "0.11"
