[package]
name = "chess-player-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.2"
wit-bindgen = "0.45.0"

[build-dependencies]
wit-bindgen = "0.45.0"
